trigger:
 - none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
        versionSpec: 19.x
    displayName: Install Node.js
  - bash:
      npm install sfdx-cli --global
    displayName: Install Salesforce CLI
  - bash:
      sfdx force:auth:jwt:grant --client-id $(SFDX_CLIENT_ID) --jwt-key-file $(SFDX_JWT_KEY_PATH) --username $(SFDX_USERNAME)  --set-default-dev-hub --alias MyOrgAlias
    displayName: Authorize salesforce org
  - bash:
      sfdx force:source:deploy -p force-app/main/default -u MyOrgAlias
    displayName: Deploy source code to Dev Org
  - bash: |
      cd ops
      npm install
      node ./dataSetup.js
    displayName: load test data into the salesforce org
    env:
      DATA_SETUP_SF_ORG_PASSWORD: $(DATA_SETUP_SF_ORG_PASSWORD)
  - bash: |
      cd ops
      npm install
      node ./sta_v3_executeTest.js
    displayName: Execute test or test suite on V3
    env:
      V3_SERVICE_PASSWORD: $(V3_SERVICE_PASSWORD)
